In [1]:
#!pip install pydotplus

In [2]:
import pandas as pd
import numpy as np
from sklearn import tree, metrics
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Loading and preprocessing data

In [3]:
features = pd.read_csv('../data/linreg_cleaned.csv')

In [4]:
features.head()

,name,price,neighbourhood_cleansed,room_type,minimum_nights,accommodates,bedrooms,beds,bathroom_count,bathroom_type
0,Nashville Charm,40.0,District 6,Private room,30,2,2.0,3.0,1.0,private bath
1,Large Main Suite near Lake *ladies only NS plz,45.0,District 12,Private room,30,1,1.0,1.0,1.0,private bath
2,Vandy/Belmont/10 mins to Broadway - Sunny 800 ...,90.0,District 18,Entire home/apt,2,4,2.0,2.0,1.0,bath
3,"SuperSweetSTUDIO, jacuzzi, open Nov 23, 6 mo",39.0,District 12,Private room,30,3,1.0,5.0,1.0,private bath
4,"MorningstarHouse, monthly room- open Aug 19",33.0,District 12,Private room,30,1,1.0,3.0,1.0,shared bath

In [5]:
# divide the variables into X and y 

X= features[['neighbourhood_cleansed', 'room_type', 'minimum_nights','accommodates',
             'bedrooms','beds','bathroom_count', 'bathroom_type']]
y= features.price

In [6]:
# One-hot encode all features in X.
X = pd.get_dummies(X)
X.head()

,minimum_nights,accommodates,bedrooms,beds,bathroom_count,neighbourhood_cleansed_District 1,neighbourhood_cleansed_District 10,neighbourhood_cleansed_District 11,neighbourhood_cleansed_District 12,neighbourhood_cleansed_District 13,...,neighbourhood_cleansed_District 8,neighbourhood_cleansed_District 9,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room,bathroom_type_bath,bathroom_type_none,bathroom_type_private bath,bathroom_type_shared bath
0,30,2,2.0,3.0,1.0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,30,1,1.0,1.0,1.0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
2,2,4,2.0,2.0,1.0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
3,30,3,1.0,5.0,1.0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
4,30,1,1.0,3.0,1.0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1

In [7]:
# Call train_test_split on X, y. Make the test_size = 0.25, and random_state = 246
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 246)

# Modelling

In [8]:
# Fit the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)
# Evaluate the model  
model.score(X_train, y_train), model.coef_

(0.03341333006509151,
 array([ 5.62340984e-01,  7.08501534e+00,  1.22528171e+01, -5.07851906e+00,
         8.91639130e+01, -6.57849506e+01, -3.54131572e+01,  1.43816596e+01,
        -1.00669381e+02,  8.73431231e+02, -7.58291540e+01,  3.57373219e+01,
        -5.62819691e+01, -4.09715672e+01, -9.24360763e+00,  4.16827582e+01,
        -1.00603229e+02,  5.51001779e+01, -5.27646949e+01, -8.98855097e+01,
         6.35127450e+01, -1.43243898e+00,  2.10272563e+01, -4.70173360e+01,
        -5.84170594e+01,  5.24486536e+01, -8.51227739e+01,  1.05907736e+01,
        -5.53069740e+01, -1.27786478e+01, -7.80856698e+01, -5.66590624e+01,
         2.99322863e+02, -8.12841043e+01, -8.87111872e+01, -8.36163326e+01,
        -5.14560418e+01, -3.07601145e+01, -6.76229985e+01, -4.15174798e+01,
        -4.32750181e+02,  8.67581115e+02, -2.28819926e+02, -2.06011007e+02,
         2.14592191e+02, -1.89867456e+02, -8.11861713e+00, -1.66061181e+01]))

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Load the data
data = pd.read_csv('../data/linreg_cleaned.csv')

# Separate features and target variable
X = data[['neighbourhood_cleansed','room_type','bathroom_type','minimum_nights','accommodates','bedrooms','beds','bathroom_count']]
y = data['price']

# Define the categorical and continuous features
categorical_features = ['neighbourhood_cleansed','room_type','bathroom_type']
continuous_features = ['minimum_nights','accommodates','bedrooms','beds','bathroom_count']

# Define the preprocessing steps for categorical and continuous features
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), categorical_features),
    ])

# Define the linear regression model
linear_model = LinearRegression()

# Define the decision tree model
tree_model = DecisionTreeRegressor(max_depth=5)

# Combine the models using VotingRegressor
ensemble_model = VotingRegressor(estimators=[('linear', linear_model), ('tree', tree_model)])

# Create the pipeline
pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('ensemble', ensemble_model)])

# Fit the pipeline
pipeline.fit(X_train, y_train)

# Make predictions
'''
sample_data = pd.DataFrame({
   'cat_var1': ['A'],
    'cat_var2': ['X'],
    'cat_var3': ['M'],
    'cat_var4': ['G'],
    'cat_var5': ['P'],
    'cont_var1': [1500],
    'cont_var2': [3],
    'cont_var3': [2],
    'cont_var4': [0.5],
    'cont_var5': [2000]
})
'''

predictions = pipeline.predict(X_test)
print("Predicted prices:")
print(predictions)

In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Load the data into a pandas DataFrame
data = pd.read_csv('../data/linreg_cleaned.csv')

# Separate the features and target variable
categorical_vars = ['neighbourhood_cleansed','room_type','bathroom_type']
continuous_vars = ['minimum_nights','accommodates','bedrooms','beds','bathroom_count']
target_var = 'price'

X_categorical = data[categorical_vars]
X_continuous = data[continuous_vars]
y = data[target_var]

# Perform one-hot encoding on the categorical variables
X_categorical_encoded = pd.get_dummies(X_categorical)

# Combine the categorical and continuous features
X = pd.concat([X_categorical_encoded, X_continuous], axis=1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the individual models
linear_model = LinearRegression()
tree_model = DecisionTreeRegressor(random_state=42)

linear_model.fit(X_train, y_train)
tree_model.fit(X_train, y_train)

# Combine the models into an ensemble
ensemble = VotingRegressor(estimators=[('linear', linear_model), ('tree', tree_model)])

# Fit the ensemble model
ensemble.fit(X_train, y_train)

# Make predictions using the ensemble model
ensemble_predictions = ensemble.predict(X_test)

# Evaluate the performance of the ensemble
mse = mean_squared_error(y_test, ensemble_predictions)
r2 = r2_score(y_test, ensemble_predictions)

print("Ensemble Performance:")
print("Mean Squared Error (MSE):", mse)
print("R-squared:", r2)

Ensemble Performance:
Mean Squared Error (MSE): 128476.5301975459
R-squared: 0.32654628029165644